### ISSUE TITLE
golang example

### ISSUE THREAD

**Issue by gedw99** [andrew-farries/pgroll-grpc#1]
hey @andrew-farries 

thanks for this.

I was wondering if there is a demo repo using golang where we can play with different schemas and how the changing schema effects the middle tier code. 

BTW the docs on the blog and comparisons with other approaches is really well done. Huge thanks you for that. https://xata.io/blog/zero-downtime-schema-migrations-postgresql

**Comment by andrew-farries** [comment]
Thanks for the comments on the blog 🙏  There is also a [Youtube video](https://youtu.be/-1aO6UznfI0?si=u84-czHG4jhJHnlw ) that covers similar ground to the blog post. 

We also have a [demo repo](https://github.com/xataio/pgroll-demo) for `pgroll`.

The video includes a runthrough of the demo repo starting at [23:13](https://youtu.be/-1aO6UznfI0?si=W6as93uIv9lOzYc_&t=1393).
